# Generated by Django 4.0.4 on 2022-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id', 'email', 'first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='prc_pic',
            field=models.ImageField(blank=True, height_field=80, null=True, upload_to='static/media/images/', width_field=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider_type',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist')], default='N/A', max_length=20),
        ),
    ]
