# Generated by Django 4.0.4 on 2022-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
