# Generated by Django 4.0.4 on 2022-04-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider_type',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist')], default='N/A', max_length=100),
        ),
    ]
