# Generated by Django 4.0.4 on 2022-04-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRejectModel',
            fields=[
                ('entry_num', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('explanation', models.CharField(max_length=500)),
                ('medical_order', models.CharField(max_length=255)),
                ('others', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=500)),
                ('from_p', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsrefs.acceptrejectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRef',
            fields=[
                ('request_num', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_type', models.CharField(choices=[('PADR', 'Patient - Doctor'), ('PAPH', 'Patient - Pharmacist'), ('DRPH', 'Doctor - Pharmacist'), ('DRDR', 'Doctor - Doctor'), ('PHPH', 'Pharmacist - Pharmacist')], default='PADR', max_length=4)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_for_consultation', models.CharField(max_length=1024)),
                ('appointment_date', models.DateField()),
                ('findings', models.CharField(blank=True, max_length=1024, null=True)),
                ('session', models.CharField(blank=True, max_length=512, null=True)),
                ('request', models.CharField(blank=True, max_length=512, null=True)),
                ('prescription', models.CharField(blank=True, max_length=512, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acceptrejectmodel',
            name='request_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsrefs.requestref'),
        ),
    ]
