# Generated by Django 4.0.4 on 2022-04-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_num', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_type', models.CharField(choices=[('PADR', 'Patient - Doctor'), ('PAPH', 'Patient - Pharmacist'), ('DRPH', 'Doctor - Pharmacist'), ('DRDR', 'Doctor - Doctor'), ('PHPH', 'Pharmacist - Pharmacist')], default='PADR', max_length=4)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_for_consultation', models.CharField(max_length=1024)),
                ('appointment_date', models.DateField()),
                ('findings', models.CharField(blank=True, max_length=1024, null=True)),
                ('session', models.CharField(blank=True, max_length=512, null=True)),
                ('request', models.CharField(blank=True, max_length=512, null=True)),
                ('prescription', models.CharField(blank=True, max_length=512, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
