# Generated by Django 4.0.4 on 2022-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptrejectmodel',
            name='entry_num',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
