# Generated by Django 4.0.4 on 2022-04-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0002_rename_request_requestref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRejectModel',
            fields=[
                ('entry_num', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('recommendation', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('explanation', models.CharField(max_length=500)),
                ('medical_order', models.CharField(max_length=255)),
                ('others', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=10)),
                ('request_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsrefs.requestref')),
            ],
        ),
    ]
