# Generated by Django 4.0.4 on 2022-04-26 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0002_alter_acceptrejectmodel_entry_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptrejectmodel',
            name='entry_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
