# Generated by Django 4.0.4 on 2022-04-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0003_acceptrejectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=500)),
                ('from_p', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestsrefs.acceptrejectmodel')),
            ],
        ),
    ]
