# Generated by Django 4.0.4 on 2022-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0004_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
