# Generated by Django 4.0.4 on 2022-04-26 06:11

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('requestsrefs', '0005_alter_transactionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptrejectmodel',
            name='entry_num',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
